from __future__ import annotations

from app.telegram_admin.client import (
    TelegramAdminClient,
    TelegramAdminConfig,
    TelegramAdminDelivery,
    TelegramAdminTransport,
)
from app.telegram_admin.command_processor import (
    AdminCommandProcessingResult,
    HttpxTelegramAdminCommandTransport,
    TelegramAdminCommandTransport,
    process_telegram_admin_commands,
)
from app.telegram_admin.commands import (
    ADMIN_COMMANDS,
    PUBLIC_ADMIN_RESERVED_COMMANDS,
    PUBLIC_COMMANDS,
    PUBLIC_MENU_BUTTON_ROWS,
    AdminCommandResponse,
    TelegramAdminCommandService,
    format_help_response,
    format_public_admin_reserved_response,
    format_public_donate_response,
    format_public_help_response,
    format_public_menu_response,
    format_public_social_response,
    format_start_response,
    normalize_admin_command,
    public_menu_reply_markup,
)
from app.telegram_admin.draft_router import (
    ADMIN_DRAFT_DELIVERY_STATUSES,
    ADMIN_DRAFT_TYPES,
    AdminDraftPersistenceResult,
    AdminDraftRecord,
    AdminDraftRoutingResult,
    admin_draft_path_for_run,
    build_admin_drafts,
    format_admin_scan_report,
    format_blocked_report,
    format_lastscan_report,
    format_near_report,
    format_status_report,
    persist_admin_drafts,
    route_admin_scan_report,
)
from app.telegram_admin.native_menu import (
    TelegramNativeCommandMenuCleanupResult,
    clear_telegram_native_command_menu,
)

__all__ = [
    "ADMIN_COMMANDS",
    "ADMIN_DRAFT_DELIVERY_STATUSES",
    "ADMIN_DRAFT_TYPES",
    "PUBLIC_ADMIN_RESERVED_COMMANDS",
    "PUBLIC_COMMANDS",
    "PUBLIC_MENU_BUTTON_ROWS",
    "AdminCommandProcessingResult",
    "AdminCommandResponse",
    "AdminDraftPersistenceResult",
    "AdminDraftRecord",
    "AdminDraftRoutingResult",
    "HttpxTelegramAdminCommandTransport",
    "TelegramAdminClient",
    "TelegramAdminCommandService",
    "TelegramAdminCommandTransport",
    "TelegramAdminConfig",
    "TelegramAdminDelivery",
    "TelegramAdminTransport",
    "TelegramNativeCommandMenuCleanupResult",
    "admin_draft_path_for_run",
    "build_admin_drafts",
    "clear_telegram_native_command_menu",
    "format_admin_scan_report",
    "format_blocked_report",
    "format_help_response",
    "format_lastscan_report",
    "format_near_report",
    "format_public_admin_reserved_response",
    "format_public_donate_response",
    "format_public_help_response",
    "format_public_menu_response",
    "format_public_social_response",
    "format_start_response",
    "format_status_report",
    "normalize_admin_command",
    "persist_admin_drafts",
    "process_telegram_admin_commands",
    "public_menu_reply_markup",
    "route_admin_scan_report",
]
